[build]
#   publish = "public"
  command = "hugo -s exampleSite --config=config.toml"

[context.production.environment]
  HUGO_VERSION = "0.49"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.49"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.49"